export default strings = {
    // App
    FACEBOOK_ID: '327743644352620',
    ACCESS_TOKEN_STORAGE_KEY: 'TOKEN',


    // Welcome
    welcomeMessage: 'Join all the action now',
    createAccount: 'Create Account',
    alreadyAUser: 'Already a user?',
    login: 'Log in',
    pressBackAgain: 'Touch again to exit',

    // Signup
    signupWithFb: 'Sign up with Facebook',
    phoneNumberInputPlaceholder: 'Phone Number',
    confirmPasswordPlaceholder: 'Confirm password',
    signup: 'Sign up',
    acceptLegal: 'I accept the',
    termsOfService: 'Terms of Service',
    and: 'and',
    privacyConditions: 'Privacy Conditions',
    signupSuccess: 'Signup completed successfully',
    signupFailed: 'Signup failed',
    ineligiblePassword: 'Password is not eligible. Please make sure the password is at least 8 characters long' +
        'and contains lowercase, uppercase, numeric and special characters.',
    incorrectConfirmPassword: 'Confirm password contains a different value from password.',
    acceptLegalConditions: 'You need to accept the legal conditions before proceeding.',
    networkConnectionProblem: 'Connection timed out',

    // Login
    loginWithFb: 'Log in with Facebook',
    or: 'or',
    passwordInputPlaceholder: 'Password',
    forgotPassword: 'Forgot your password?',
    loginFailed: 'Login failed',

    // Basic Info
    insertName: 'Your name here',
    save: 'Save',
    successfullySaved: 'Successfully saved',

    // Search bar header
    searchBarPlaceholder: 'Search',
    surpriseMe: 'Surprise me',
    notifications: 'Notifications',

    // nav footer
    nearby: 'Nearby',
    search: 'Search',
    addAPlace: 'Add a place',
    myProfile: 'My profile',
    settings: 'Settings',

    // Nearby
    trending: 'Trending',
    places: 'Places',
    new: 'New',
    friends: 'Friends',
    challenges: 'Challenges',
    location: 'Location',
    locating: 'Locating...',
    appWantsToEnableLocation: 'Zeila wants to enable location services',
    enableLocation: 'Please enable location services',
    unableToLocate: 'Unable to get your location',
    manualLocationPlaceholder: 'Addis Ababa, Bole',
    invalidLocation: 'The location you entered could not be found',
    waitUntilLocated: 'Please wait while you are being located',
    setLocationManually: 'Set location manually',
    setYourLocation: "You haven't set a location",
    showInEmbeddedMap: 'Show on map',
    openInMaps: 'Get Direction in Maps',
    nearbyPlaces: 'Nearby Places',
    noNearbyPlaces: 'No places nearby',
    noCategoryPlacesNearbyPrefix: 'No',
    noCategoryPlacesNearbySuffix: 'in the area',
    noNewPlaces: 'There are no new places',
    noTrendingPlaces: 'There are no trending places',
    addToBookmarks: 'Add to bookmarks',
    bookmarkAdded: 'Added to bookmarks',
    bookmarkRemoved: 'Removed from bookmarks',
    unableToBookmark: 'Bookmark failed',
    away: 'away',
    ok: 'OK',
    cancel: 'Cancel',
    noLikes: 'No Likes',
    oneLike: '1 Like',
    likes: 'Likes',
    refreshLocation: 'Refresh my location',

    // Search
    categories: 'Categories',
    filters: 'Filters',
    noPlaces: 'No places to show',
    placeNotFound: 'not found',
    addToZeila: 'Add to Zeila',
    editCategoryOrder: 'Edit category order',
    finishCategoryOrder: 'Save category order',
    cancelCategoryOrder: 'Cancel new category order',
    lockCategoryOrderScroll: 'Lock/Unlock scroll',

    // business profile
    readMoreOverview: 'more',
    readMoreReviewText: 'Continue Reading',
    rateAPlace: 'Rate this place',
    youHaveRatedThisPlace: 'You have rated this place',
    removeMyRating: 'Unrate',
    noRatings: 'No Ratings',
    photos: 'Photos',
    seeAll: 'See All',
    reviews: 'Reviews',
    you: 'You',
    wroteAReview: 'Wrote A Review',
    elipsis: '...',
    uploadMedia: 'Upload Photo',
    sendReview: 'Send Review',
    readReviewGuidelines: 'Read review guidelines',
    readReviewGuidelinesPrompt: 'Do you want to read the guidelines of writing an acceptable review?',
    writeAReviewPlaceholder: 'Write a review here...',
    reviewAdded: 'Review added',
    operationFailed: 'Operation failed',
    photoUploadSuccessful: 'Photo uploaded successfully',
    takeFromCamera: 'Camera',
    pickFromStorage: 'Storage',
    uploadingPhoto: 'Uploading photo',

    // CategoryGrid texts
    restaurants: 'Restaurants',
    hospitals: 'Hospitals',
    bars: 'Bars',
    pharmacies: 'Pharmacies',
    events: 'Events',
    gyms: 'Gyms',
    garages: 'Garages',
    parks: 'Parks',
    hotels: 'Hotels',
    icecreams: 'Icecreams',
    cafes: 'Cafes',
    guestHouses: 'Guest Houses',
    pastries: 'Pastries',
    licenseSchools: 'License Schools',

    // Search filter texts
    category: 'Category',
    price: 'Price',
    services: 'Services',
    openDays: 'Open Days',
    openHours: 'Open Hours',
    vibe: 'Vibe',

    any: 'Any',
    closeBy: 'Close By',
    notSoFar: 'Not So Far',
    cheap: 'Cheap',
    notSoExpensive: 'Not So Expensive',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',

    // Settings
    logout: 'Logout',
    changeBasicInfo: 'Change your name/picture'
};